name: Deployment to Andasy With remote builder
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarksgroup/andasy-action@main
        env:
          # Set access token
          ANDASY_ACCESS_TOKEN: ${{ secrets.ANDASY_ACCESS_TOKEN }}
        with:
          # Specifying custom deployment directory, relative to the root of the repository
          project_path: remote-builder
          # Using remote builder instead of local one. This is not recommended.
          build_mode: remote
